### ISSUE TITLE
AgoraRtcEngineKit/AgoraRtcEngineKit.h file not found.

### ISSUE THREAD

**Issue by dmyma** [AgoraIO-Community/Agora-Screen-Sharing-iOS#10]
I cloned the repo and tried to run it, but I have an error AgoraRtcEngineKit/AgoraRtcEngineKit.h file not found, what should I do? Thank you

**Comment by jonassu** [comment]
Please download the [Agora Video SDK](https://www.agora.io/en/blog/download/). Unzip the downloaded SDK package and copy the libs/AograRtcEngineKit.framework file from the SDK folder into the sample application's Agora-Screen-Sharing-iOS-Broadcast folder.
